apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e4wfzwwms-java-springboot
  janus-idp.io/tekton: e4wfzwwms-java-springboot
  backstage.io/kubernetes-id: e4wfzwwms-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e4wfzwwms-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
